version: '3.8'

services:
  disco:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATA_DIR=app/data
      # Add your other environment variables here
      - JWT_SECRET=your-production-jwt-secret
      - WEBCONTAINER_API_KEY=your-webcontainer-api-key
      - REDIS_URL=redis://redis:6379
    volumes:
      # Mount host directory to container's data directory
      - ./local_data:/app/data
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: