[build]
builder = "DOCKERFILE"
watchPatterns = ["src/**", "package.json", "tsconfig.json"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1
region = "us-west1"
sleepApplication = false

[deploy.runtime]
memoryLimit = "1024Mi"
cpuLimit = "1.0"

[deploy.scaling]
minReplicas = 1
maxReplicas = 2
targetCPUPercent = 70
targetMemoryPercent = 80

[deploy.cron]
schedule = "0 */6 * * *"
command = "node scripts/cleanup-stale-containers.js"