name: Railway Configuration Validator

on:
  push:
    paths: 
      - 'railway.toml'
      - 'railway.json' 
      - 'railpack.json'
      - 'Dockerfile'
      - 'src/**/*.ts'
      - 'src/**/*.js'
      - 'package.json'
      - '.env.example'
  pull_request:
    paths:
      - 'railway.toml'
      - 'railway.json'
      - 'railpack.json' 
      - 'Dockerfile'
      - 'src/**/*.ts'
      - 'src/**/*.js'
      - 'package.json'
      - '.env.example'

jobs:
  validate-railway-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Enable Corepack
        run: corepack enable
          
      - name: Install dependencies
        run: yarn install --immutable
        
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH
          
      - name: Validate TypeScript compilation
        run: yarn build
        
      - name: Run ESLint
        run: yarn lint
        
      - name: Validate Railway configuration
        run: |
          node scripts/railway-validation/validator.cjs
          
      - name: Check environment variables configuration
        run: |
          node scripts/railway-validation/env-validator.cjs
          
      - name: Validate CORS and auth configuration
        run: |
          node scripts/railway-validation/auth-validator.cjs
          
      - name: Generate validation report
        run: |
          node scripts/railway-validation/generate-report.cjs > railway-validation-report.md
          
      - name: Upload validation report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: railway-validation-report
          path: railway-validation-report.md
          
      - name: Comment PR with validation results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('railway-validation-report.md', 'utf8');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Railway Configuration Validation Report\n\n${report}`
            });